title: Segun Famisa
email:
description: >-
  Personal blog for Segun Famisa.
url: "https://segunfamisa.com"
baseurl: ""
lang: en
timezone: Europe/Berlin

author:
  name: Segun Famisa

seo:
  locale: en_US
  twitter:
  image:

atproto:
  enabled: true
  handle: segunfamisa.com
  did: did:plc:a5mekodp4afxadlpr4hp2wci
  profile_url:

standard_site:
  enabled: true
  publication_at_uri: at://did:plc:a5mekodp4afxadlpr4hp2wci/site.standard.publication/3mm2oa7vz5327

nav:
  - title: home
    url: /
  - title: posts
    url: /posts/
  - title: photos
    url: /photos/
  - title: about
    url: /about/

social:
  - title: github
    url: https://github.com/segunfamisa
  - title: bluesky
    url: https://bsky.app/profile/did:plc:a5mekodp4afxadlpr4hp2wci
  - title: unsplash
    url: https://unsplash.com/segunfamisa
  # - title: rss
    # url: /feed.xml

home:
  recent_posts: 3

tag_pages:
  enabled: true
  show_in_nav: false

search:
  enabled: true
  modal: true
  show_in_nav: true
  shortcut: true
  json_path: /search.json
  limit: 8
  library_url: https://cdn.jsdelivr.net/npm/simple-jekyll-search@1.10.0/dest/simple-jekyll-search.min.js

collections:
  albums:
    output: true
    permalink: /photos/albums/:slug/
  photos:
    output: true
    permalink: /photos/albums/:path/

permalink: /posts/:slug

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - archive
